name: flutter_notebook_chapter_46
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^0.0.11
  gap: ^3.0.1
  readmore: ^3.0.0
  google_fonts: ^6.3.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
